name: Select Deploy Test
on:
    workflow_dispatch: 
        inputs:
            environment_enum:
                description: "Environment Enum"
                required: true
                type: choice
                options:
                    - Town21
                    - Town22
                    - Town23
                    - Town24
                    - Town25
                    - Town30
            environment:
                description: "Evironment"
                required: false
                type: environment
            
jobs:
    dropsdown:
        runs-on: windows-latest
        steps:
            - name: Select Server
              run: echo "Environment Enum ${{ inputs.environment_enum }}, Environment ${{ inputs.environment }}"